name = "SimpleKiteControllers"
uuid = "6b1669b4-da33-4b52-bbac-669bd9da52ef"
authors = ["Uwe Fechner <u.fechner-1@tudelft.nl> and contributors"]
version = "1.0.0-DEV"

[deps]
KiteModels = "b94af626-7959-4878-9336-2adc27959007"

[compat]
KiteModels = "0.8.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
